# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{enhanced_marc}
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ross Singer"]
  s.date = %q{2009-11-17}
  s.description = %q{A set of enhancements to ruby-marc to make parsing MARC data easier}
  s.email = %q{rossfsinger@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "Changes",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "enhanced_marc-0.1.gem",
     "enhanced_marc.gemspec",
     "lib/enhanced_marc.rb",
     "lib/enhanced_marc/book_record.rb",
     "lib/enhanced_marc/book_type.rb",
     "lib/enhanced_marc/computer_record.rb",
     "lib/enhanced_marc/computer_type.rb",
     "lib/enhanced_marc/leader.rb",
     "lib/enhanced_marc/leftovers.rb",
     "lib/enhanced_marc/map_record.rb",
     "lib/enhanced_marc/map_type.rb",
     "lib/enhanced_marc/mixed_record.rb",
     "lib/enhanced_marc/mixed_type.rb",
     "lib/enhanced_marc/reader.rb",
     "lib/enhanced_marc/record.rb",
     "lib/enhanced_marc/record_type.rb",
     "lib/enhanced_marc/score_record.rb",
     "lib/enhanced_marc/score_type.rb",
     "lib/enhanced_marc/serial_record.rb",
     "lib/enhanced_marc/serial_type.rb",
     "lib/enhanced_marc/sound_record.rb",
     "lib/enhanced_marc/sound_type.rb",
     "lib/enhanced_marc/visual_record.rb",
     "lib/enhanced_marc/visual_type.rb",
     "lib/enhanced_marc/xmlreader.rb",
     "pkg/enhanced_marc-0.1.5.gem",
     "pkg/enhanced_marc-0.1.gem",
     "pkg/enhanced_marc-0.1.tgz",
     "pkg/enhanced_marc-0.1.zip",
     "pkg/enhanced_marc-0.1/Changes",
     "pkg/enhanced_marc-0.1/LICENSE",
     "pkg/enhanced_marc-0.1/README",
     "pkg/enhanced_marc-0.1/Rakefile",
     "pkg/enhanced_marc-0.1/test/ts_enhanced_marc.rb",
     "test/ts_enhanced_marc.rb"
  ]
  s.homepage = %q{http://github.com/rsinger/enhanced-marc/tree}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A DSL for MARC data}
  s.test_files = [
    "test/ts_enhanced_marc.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<marc>, [">= 0"])
      s.add_runtime_dependency(%q<locale>, [">= 0"])
    else
      s.add_dependency(%q<marc>, [">= 0"])
      s.add_dependency(%q<locale>, [">= 0"])
    end
  else
    s.add_dependency(%q<marc>, [">= 0"])
    s.add_dependency(%q<locale>, [">= 0"])
  end
end

