require 'marc'
require 'locale/info'
require File.dirname(__FILE__) + '/enhanced_marc/reader'
require File.dirname(__FILE__) + '/enhanced_marc/record'
require File.dirname(__FILE__) + '/enhanced_marc/leader'
require File.dirname(__FILE__) + '/enhanced_marc/book_record'
require File.dirname(__FILE__) + '/enhanced_marc/serial_record'
require File.dirname(__FILE__) + '/enhanced_marc/visual_record'
require File.dirname(__FILE__) + '/enhanced_marc/mixed_record'
require File.dirname(__FILE__) + '/enhanced_marc/map_record'
require File.dirname(__FILE__) + '/enhanced_marc/score_record'
require File.dirname(__FILE__) + '/enhanced_marc/sound_record'
require File.dirname(__FILE__) + '/enhanced_marc/computer_record'
require File.dirname(__FILE__) + '/enhanced_marc/record_type'
require File.dirname(__FILE__) + '/enhanced_marc/book_type'
require File.dirname(__FILE__) + '/enhanced_marc/computer_type'
require File.dirname(__FILE__) + '/enhanced_marc/map_type'
require File.dirname(__FILE__) + '/enhanced_marc/mixed_type'
require File.dirname(__FILE__) + '/enhanced_marc/score_type'
require File.dirname(__FILE__) + '/enhanced_marc/serial_type'
require File.dirname(__FILE__) + '/enhanced_marc/sound_type'
require File.dirname(__FILE__) + '/enhanced_marc/visual_type'
